# Generated by Django 2.2.5 on 2020-03-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_to_diary', '0004_auto_20200309_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='current_position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='position',
        ),
    ]
