# Generated by Django 2.2.5 on 2020-03-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_to_diary', '0005_auto_20200309_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inputa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.TextField()),
                ('last', models.TextField()),
                ('report', models.TextField()),
                ('email', models.TextField()),
                ('address', models.TextField()),
                ('address2', models.TextField()),
                ('state', models.IntegerField()),
                ('state_zip', models.IntegerField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Input',
        ),
    ]
