# Generated by Django 2.2.5 on 2020-03-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day_to_diary', '0006_auto_20200309_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inputa',
            name='state',
            field=models.TextField(),
        ),
    ]
